# Generated by Django 5.1.6 on 2025-06-17 23:29

from django.db import migrations, models
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Profile = apps.get_model('portfolio', 'CreativeProfile')
    for profile in Profile.objects.all():
        base_slug = slugify(profile.name)
        slug = base_slug
        counter = 1
        while Profile.objects.filter(slug=slug).exclude(id=profile.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        profile.slug = slug
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_creativeprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="creativeprofile",
            name="skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="creativeprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="creativeprofile",
            name="bio",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="creativeprofile",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(generate_slugs),  # ✅ Populate slugs after adding the field
    ]
