# Generated by Django 5.1.6 on 2025-06-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_creativeprofile_skills_creativeprofile_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativeprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
